platform :macos, '11.0'
workspace 'day06'

targets = ['task1', 'task2']

targets.each do |target|
  target_project = "#{target}/#{target}.xcodeproj"  
  target target do
    project target_project
      use_modular_headers!
      pod 'RxRealm'
  end
end

