platform :macos, '11.0'
workspace 'day07'

targets = ['task3']

targets.each do |target|
  target_project = "#{target}/#{target}.xcodeproj"  
  target target do
    project target_project
      use_modular_headers!
      pod 'Alamofire'
  end
end


